### ISSUE TITLE
Add support for sidekiqswarm

### ISSUE THREAD

**Issue by jwhitcraft** [fastly/sidekiq-prometheus#14]
Hello,

We are trying to use this gem, but since we use `sidekiqswarm` to start our workers, it throws stack traces because the port that the metrics are served from are already in use.

<detail>
```
#<Thread:0x00007fbb8a6a6088@/Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq_prometheus-1.0.1/lib/sidekiq_prometheus.rb:184 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        12: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq_prometheus-1.0.1/lib/sidekiq_prometheus.rb:185:in `block in metrics_server'
        11: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/handler/webrick.rb:33:in `run'
        10: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/handler/webrick.rb:33:in `new'
         9: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/webrick/httpserver.rb:47:in `initialize'
         8: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/webrick/server.rb:108:in `initialize'
         7: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/webrick/server.rb:127:in `listen'
         6: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:65:in `create_listeners'
         5: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/socket.rb:762:in `tcp_server_sockets'
         4: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/socket.rb:227:in `foreach'
         3: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/socket.rb:227:in `each'
         2: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/socket.rb:764:in `block in tcp_server_sockets'
         1: from /Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/socket.rb:201:in `listen'
/Users/jwhitcraft/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/socket.rb:201:in `bind': Address already in use - bind(2) for 0.0.0.0:9359 (Errno::EADDRINUSE)
```
</detail>

I used this command to start with:
`SIDEKIQ_COUNT=2 SIDEKIQ_CONCURRENCY=1 MAX_THREADS=1 RAILS_ENV=production bundle exec sidekiqswarm -e production -C config/sidekiq.yml`

But if I change `SIDEKIQ_COUNT` to be `1` it starts up fine, with out issues.

**Comment by we4tech** [comment]
Hi @jwhitcraft, I am involved with a project where we are planning to use this gem with a giant Sidekiqswarm setup. @gtan66 is mainly working with it.

Our planning is to use pushgateway per pod and let sidekiq push to local. 

Let me know if you are interested to know the progress whenever we have.

**Comment by leklund** [comment]
Because the gem is binding a single host:port for the metrics server it won't work with `sidekiqswarm` in its current configuration. One option would be to rescue that error and increment the port number so each Sidekiq process would have it's own metrics server to scrape. The problem with that solution is that metrics wouldn't be aggregated for that host.  

The ruby client offers a `DirectFileStore` for sharing metrics between processes and that might be an option. This gem would need to be updated to support that store and also ensure that only one process ran the rack server for exporting metrics. The DirectFileStore has some caveats though (https://github.com/prometheus/client_ruby#directfilestore-caveats-and-things-to-keep-in-mind). I will try to take a look at implementing the shared file store so we can support multiple process swarms.

**Comment by jwhitcraft** [comment]
@leklund yeah, i understand the problem there, not sure if it's an option or not, but would if it would work with this: https://github.com/discourse/prometheus_exporter gem, that might be the best idea for the swarm stuff.  Currently I'm just writing my own custom collector for more advance sidekiq stuff as they don't want to include them in the core.
